language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build

elixir:
  - 1.8.1

otp_release:
  - 21.2

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix compile
  - mix coveralls --trace
  - travis_wait 20 mix dialyzer --halt-exit-status
  # - mix dialyzer --halt-exit-status
  - mix format --check-formatted
  - mix credo -a

# Leave only .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build

sudo: false
